export const IconReference = {
	'bell:fill': 'solar:bell-bold',
	'chart_line': 'lucide:chart-line',
	'close': 'iconamoon:close-bold',
	'dashboard': 'akar-icons:dashboard',
	'check': 'ph:check-fat-fill',
	'check:all': 'ic:round-done-all',
	'download:cloud': 'bytesize:download',
	'eye': 'tabler:eye',
	'eye-off': 'tabler:eye-off',
	'exam': 'ph:exam',
	'filter': 'tabler:filter',
	'heart-hand': 'mingcute:heart-hand-line',
	'chevron-left': 'ic:round-chevron-left',
	'chevron-up': 'ph:caret-up-bold',
	'chevron-right': 'ic:round-chevron-right',
	'chevron-down': 'ph:caret-down-bold',
	'exit': 'uil:exit',
	'file-list': 'ri:file-list-2-line',
	'loading-fill': 'mingcute:loading-3-fill',
	'menu': 'cuida:menu-outline',
	'preferences': 'pajamas:preferences',
	'pdf': 'ph:file-pdf-fill',
	'scheduler': 'lucide:book-marked',
	'search': 'stash:search-solid',
	'share': 'material-symbols:share-outline',
	'x-ray': 'mdi:x-ray-box-outline',
} as const;

export type IconKey = keyof typeof IconReference;
