export type SchedulingDTO = {
  id: string;
  active: boolean;
  birth: string;
  canceled_at: string | null;
  confirmed: string | null;
  date_atendance: string;
  start: string;
  end: string;
  exame: string | null;
  gender: { key: string; label: string };
  laudo: string | null;
  modality: string;
  patient_id: string;
  patient_name: string;
  queue_type: string;
  paid: boolean;
  procedure: string;
  status: string;
};
